# Generated by Django 2.2.4 on 2023-09-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
